import base64
import json
import logging
import os
from datetime import UTC, datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from jinja2 import Environment, FileSystemLoader

from app.config import ALERT_EMAIL, API_URL, FROM_EMAIL, FRONTEND_URL, GMAIL_TOKEN_B64
from app.curator import ContentCurator
from app.database import SessionLocal
from app.models import Content, DigestLog, User

logger = logging.getLogger(__name__)

# Setup Jinja Environment
TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), 'templates')
jinja_env = Environment(loader=FileSystemLoader(TEMPLATE_DIR))

class EmailDeliverer:
    def __init__(self):
        self.template = jinja_env.get_template('digest.html')
        
    def render_email_html(self, user: User, articles: list[Content]) -> str:
        """Parses the LLM JSON strings and renders the final HTML string."""
        
        parsed_articles = []
        for article in articles:
            # Safely parse the JSON generated by Gemini
            summary_data = None
            if article.summary:
                try:
                    summary_data = json.loads(article.summary)
                except json.JSONDecodeError:
                    logger.error(f"Failed to parse article summary JSON for ID: {article.id}")
            
            parsed_articles.append({
                "title": article.title,
                "url": article.url,
                "summary_data": summary_data
            })
            
        return self.template.render(user=user, articles=parsed_articles, frontend_url=FRONTEND_URL, api_url=API_URL)

    def send_welcome_email(self, to_email: str) -> bool:
        """Renders and sends the Welcome email to new subscribers."""
        welcome_template = jinja_env.get_template('welcome.html')
        html_body = welcome_template.render(email=to_email, frontend_url=FRONTEND_URL, api_url=API_URL)
        return self.send_email(to_email, html_body, subject="Welcome to Briefly.ai! ✨")

    def send_pipeline_alert_email(self, error_message: str, stage: str = "Pipeline") -> bool:
        """Sends an operational alert email when the automated pipeline encounters an unhandled error."""
        recipient = ALERT_EMAIL or FROM_EMAIL
        if not recipient:
            logger.warning("No ALERT_EMAIL or FROM_EMAIL configured. Skipping pipeline alert email.")
            return False

        subject = f"🚨 Briefly.ai Pipeline Failure: {stage}"
        now_utc = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

        html_content = f"""
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
            <h2 style="color: #dc2626; margin-top: 0;">🚨 Briefly.ai Pipeline Failure</h2>
            <p>An error occurred during the automated news pipeline execution.</p>
            <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                <tr><td style="padding: 8px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Failed Stage:</td><td style="padding: 8px; border-bottom: 1px solid #e2e8f0;">{stage}</td></tr>
                <tr><td style="padding: 8px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Timestamp:</td><td style="padding: 8px; border-bottom: 1px solid #e2e8f0;">{now_utc}</td></tr>
                <tr><td style="padding: 8px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Error Detail:</td><td style="padding: 8px; color: #b91c1c; border-bottom: 1px solid #e2e8f0;"><code>{error_message}</code></td></tr>
            </table>
            <p style="color: #64748b; font-size: 12px; margin-bottom: 0;">This is an automated operational alert from Briefly.ai.</p>
        </div>
        """
        return self.send_email(recipient, html_content, subject=subject)

    def send_email(self, to_email: str, html_content: str, subject: str = "Your Daily AI News Digest"):
        """Sends an HTML email using the official Gmail API (Bypasses all cloud firewalls)"""
        
        if GMAIL_TOKEN_B64:
            try:
                # 1. Decode the Base64 token safely back into JSON string, then dictionary
                token_json_str = base64.b64decode(GMAIL_TOKEN_B64).decode('utf-8')
                creds_info = json.loads(token_json_str)
                creds = Credentials.from_authorized_user_info(creds_info)
                
                # 2. Build the Gmail API Service
                service = build('gmail', 'v1', credentials=creds)
                
                # 3. Construct the MIME message
                message = MIMEMultipart('alternative')
                message['To'] = to_email
                message['From'] = FROM_EMAIL # Best practice to match the authenticated user
                message['Subject'] = subject
                message.attach(MIMEText(html_content, 'html'))
                
                # 4. Gmail API requires a base64url encoded string
                raw_string = base64.urlsafe_b64encode(message.as_bytes()).decode()
                message_body = {'raw': raw_string}
                
                # 5. Send it using the magical HTTP API!
                service.users().messages().send(userId='me', body=message_body).execute()
                logger.info(f"Successfully emailed digest to {to_email} via native Gmail API")
                return True
                
            except Exception as e:
                logger.error(f"Gmail API Delivery Failed for {to_email}: {e}")
                return False

        # Fallback for local testing if no token provided
        logger.warning("GMAIL_TOKEN_B64 missing. Printing mock email to console instead.")
        print("\n" + "="*50)
        print(f"MOCK EMAIL SENT TO: {to_email} | SUBJECT: {subject}")
        print("="*50 + "\n")
        return True

def deliver_daily_digests():
    """Main function that curates content and sends out all emails."""
    db = SessionLocal()
    curator = ContentCurator()
    deliverer = EmailDeliverer()
    
    logger.info("Starting Daily Email Delivery process...")
    
    # 1. Get curated mapping of user -> top articles
    user_curation_map = curator.curate_for_all_users(max_articles_per_user=5)
    
    if not user_curation_map:
        logger.info("No content to deliver today.")
        db.close()
        return

    # 2. Loop through users and send emails
    for user_id, articles in user_curation_map.items():
        if not articles:
            logger.info(f"No relevant articles for User {user_id} today. Skipping email.")
            continue
            
        user = db.query(User).filter(User.id == user_id).first()
        
        logger.info(f"Preparing custom digest for {user.email} with {len(articles)} articles.")
        
        # Render the HTML
        html_body = deliverer.render_email_html(user, articles)
        
        # Send
        success = deliverer.send_email(user.email, html_body)
        
        if success:
            # Log successful delivery so we don't spam them with this again tomorrow
            for article in articles:
                log_entry = DigestLog(user_id=user.id, content_id=article.id)
                db.add(log_entry)
            db.commit()

    db.close()
    logger.info("Daily Delivery complete.")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    deliver_daily_digests()
