import os
import json
import logging
import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from jinja2 import Environment, FileSystemLoader

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from app.database import SessionLocal
from app.models import DigestLog, User, Content
from app.curator import ContentCurator
from app.config import FROM_EMAIL, GMAIL_TOKEN_B64, FRONTEND_URL, API_URL

logger = logging.getLogger(__name__)

# Setup Jinja Environment
TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), 'templates')
jinja_env = Environment(loader=FileSystemLoader(TEMPLATE_DIR))

class EmailDeliverer:
    def __init__(self):
        self.template = jinja_env.get_template('digest.html')
        
    def render_email_html(self, user: User, articles: list[Content]) -> str:
        """Parses the LLM JSON strings and renders the final HTML string."""
        
        parsed_articles = []
        for article in articles:
            # Safely parse the JSON generated by Gemini
            summary_data = None
            if article.summary:
                try:
                    summary_data = json.loads(article.summary)
                except json.JSONDecodeError:
                    logger.error(f"Failed to parse article summary JSON for ID: {article.id}")
            
            parsed_articles.append({
                "title": article.title,
                "url": article.url,
                "summary_data": summary_data
            })
            
        return self.template.render(user=user, articles=parsed_articles, frontend_url=FRONTEND_URL, api_url=API_URL)

    def send_welcome_email(self, to_email: str) -> bool:
        """Renders and sends the Welcome email to new subscribers."""
        welcome_template = jinja_env.get_template('welcome.html')
        html_body = welcome_template.render(email=to_email, frontend_url=FRONTEND_URL, api_url=API_URL)
        return self.send_email(to_email, html_body, subject="Welcome to Briefly.ai! ✨")

    def send_email(self, to_email: str, html_content: str, subject: str = "Your Daily AI News Digest"):
        """Sends an HTML email using the official Gmail API (Bypasses all cloud firewalls)"""
        
        if GMAIL_TOKEN_B64:
            try:
                # 1. Decode the Base64 token safely back into JSON string, then dictionary
                token_json_str = base64.b64decode(GMAIL_TOKEN_B64).decode('utf-8')
                creds_info = json.loads(token_json_str)
                creds = Credentials.from_authorized_user_info(creds_info)
                
                # 2. Build the Gmail API Service
                service = build('gmail', 'v1', credentials=creds)
                
                # 3. Construct the MIME message
                message = MIMEMultipart('alternative')
                message['To'] = to_email
                message['From'] = FROM_EMAIL # Best practice to match the authenticated user
                message['Subject'] = subject
                message.attach(MIMEText(html_content, 'html'))
                
                # 4. Gmail API requires a base64url encoded string
                raw_string = base64.urlsafe_b64encode(message.as_bytes()).decode()
                message_body = {'raw': raw_string}
                
                # 5. Send it using the magical HTTP API!
                service.users().messages().send(userId='me', body=message_body).execute()
                logger.info(f"Successfully emailed digest to {to_email} via native Gmail API")
                return True
                
            except Exception as e:
                logger.error(f"Gmail API Delivery Failed for {to_email}: {e}")
                return False

        # Fallback for local testing if no token provided
        logger.warning("GMAIL_TOKEN_B64 missing. Printing mock email to console instead.")
        print("\n" + "="*50)
        print(f"MOCK EMAIL SENT TO: {to_email} | SUBJECT: {subject}")
        print("="*50 + "\n")
        return True

def deliver_daily_digests():
    """Main function that curates content and sends out all emails."""
    db = SessionLocal()
    curator = ContentCurator()
    deliverer = EmailDeliverer()
    
    logger.info("Starting Daily Email Delivery process...")
    
    # 1. Get curated mapping of user -> top articles
    user_curation_map = curator.curate_for_all_users(max_articles_per_user=5)
    
    if not user_curation_map:
        logger.info("No content to deliver today.")
        db.close()
        return

    # 2. Loop through users and send emails
    for user_id, articles in user_curation_map.items():
        if not articles:
            logger.info(f"No relevant articles for User {user_id} today. Skipping email.")
            continue
            
        user = db.query(User).filter(User.id == user_id).first()
        
        logger.info(f"Preparing custom digest for {user.email} with {len(articles)} articles.")
        
        # Render the HTML
        html_body = deliverer.render_email_html(user, articles)
        
        # Send
        success = deliverer.send_email(user.email, html_body)
        
        if success:
            # Log successful delivery so we don't spam them with this again tomorrow
            for article in articles:
                log_entry = DigestLog(user_id=user.id, content_id=article.id)
                db.add(log_entry)
            db.commit()

    db.close()
    logger.info("Daily Delivery complete.")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    deliver_daily_digests()
